# Generated by Django 3.1.6 on 2021-03-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='fix-me', unique=True),
            preserve_default=False,
        ),
    ]
