# Generated by Django 3.1.6 on 2021-03-17 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_auto_20210317_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='followers',
            field=models.ManyToManyField(related_name='category_follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
