# Generated by Django 3.1.6 on 2021-03-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210318_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
