# Generated by Django 3.1.6 on 2021-04-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_post_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Sourabh Mundada', max_length=150),
            preserve_default=False,
        ),
    ]
